from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, model_validator


DISCLAIMER = (
    "Investment recommendations are educational estimates generated by AI and "
    "historical market data. They are not guaranteed financial advice. Users should "
    "perform their own research or consult a qualified financial advisor before "
    "making investment decisions."
)


class MaritalStatus(str, Enum):
    single = "single"
    married = "married"
    divorced = "divorced"
    widowed = "widowed"


class HousingType(str, Enum):
    own = "own"
    rented = "rented"


class RiskProfile(str, Enum):
    conservative = "conservative"
    moderate = "moderate"
    aggressive = "aggressive"


class PriorityLevel(str, Enum):
    high = "high"
    medium = "medium"
    low = "low"


class LoanInput(BaseModel):
    name: str
    outstanding_amount: float = Field(ge=0)
    interest_rate: float = Field(ge=0)
    monthly_emi: float = Field(ge=0)
    remaining_tenure_months: int = Field(ge=0)


class ChildExpense(BaseModel):
    name: str
    school_fees: float = Field(ge=0, default=0)
    tuition_fees: float = Field(ge=0, default=0)
    transportation_expenses: float = Field(ge=0, default=0)
    medical_expenses: float = Field(ge=0, default=0)
    monthly_maintenance_cost: float = Field(ge=0, default=0)

    @property
    def total(self) -> float:
        return (
            self.school_fees
            + self.tuition_fees
            + self.transportation_expenses
            + self.medical_expenses
            + self.monthly_maintenance_cost
        )


class FinancialGoal(BaseModel):
    goal_name: str
    goal_amount: float = Field(ge=0)
    target_year: int = Field(ge=2000)
    priority_level: PriorityLevel


class RiskAssessmentAnswers(BaseModel):
    risk_tolerance: int = Field(ge=1, le=5)
    investment_experience: int = Field(ge=1, le=5)
    time_horizon: int = Field(ge=1, le=5)
    market_understanding: int = Field(ge=1, le=5)
    loss_tolerance: int = Field(ge=1, le=5)


class UserFinancialProfile(BaseModel):
    age: int = Field(ge=18, le=100)
    marital_status: MaritalStatus
    family_members: int = Field(ge=1)
    dependent_family_members: int = Field(ge=0)
    children_count: int = Field(ge=0)
    children_ages: List[int] = Field(default_factory=list)

    monthly_salary: float = Field(ge=0)
    business_income: float = Field(ge=0, default=0)
    rental_income: float = Field(ge=0, default=0)
    freelance_income: float = Field(ge=0, default=0)
    additional_income_sources: Dict[str, float] = Field(default_factory=dict)

    housing_type: HousingType
    monthly_rent: float = Field(ge=0, default=0)
    home_loan_status: bool = False
    home_loan_outstanding_amount: float = Field(ge=0, default=0)
    home_loan_monthly_emi: float = Field(ge=0, default=0)

    loans: List[LoanInput] = Field(default_factory=list)
    child_expenses: List[ChildExpense] = Field(default_factory=list)
    monthly_expenses: Dict[str, float] = Field(default_factory=dict)
    existing_investments: Dict[str, float] = Field(default_factory=dict)
    goals: List[FinancialGoal] = Field(default_factory=list)
    risk_assessment: RiskAssessmentAnswers

    @model_validator(mode="after")
    def validate_children(self) -> "UserFinancialProfile":
        if self.children_count != len(self.children_ages):
            raise ValueError("children_count must match number of children_ages")
        return self

    @property
    def total_monthly_income(self) -> float:
        return (
            self.monthly_salary
            + self.business_income
            + self.rental_income
            + self.freelance_income
            + sum(self.additional_income_sources.values())
        )


class AllocationRecommendation(BaseModel):
    category: str
    amount: float
    explanation: str


class FinancialAnalysisResult(BaseModel):
    total_monthly_income: float
    total_monthly_expenses: float
    total_monthly_emi: float
    total_child_expenses: float
    monthly_surplus: float
    savings_rate_percent: float
    debt_to_income_ratio_percent: float
    financial_health_score: int
    debt_risk_score: int
    savings_score: int
    investment_readiness_score: int
    risk_profile: RiskProfile
    recommendations: List[AllocationRecommendation]
    disclaimer: str = DISCLAIMER


class MarketInstrumentAnalysis(BaseModel):
    symbol: str
    long_name: Optional[str] = None
    current_price: Optional[float] = None
    pe_ratio: Optional[float] = None
    pb_ratio: Optional[float] = None
    market_cap: Optional[float] = None
    revenue_growth: Optional[float] = None
    profit_growth: Optional[float] = None
    dividend_yield: Optional[float] = None
    debt_ratio: Optional[float] = None


class CoachQuestion(BaseModel):
    question: str
    language: str = Field(default="english")


class CoachAnswer(BaseModel):
    language: str
    answer: str
    disclaimer: str = DISCLAIMER


class SIPInput(BaseModel):
    monthly_investment: float = Field(gt=0)
    annual_return_percent: float = Field(gt=0)
    years: int = Field(gt=0)


class SIPResult(BaseModel):
    invested_amount: float
    estimated_value: float


class LoanCalculatorInput(BaseModel):
    principal: float = Field(gt=0)
    annual_interest_percent: float = Field(gt=0)
    tenure_months: int = Field(gt=0)


class LoanCalculatorResult(BaseModel):
    emi: float
    total_interest: float
    total_payment: float
