import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

const disclaimer =
    'Investment recommendations are educational estimates generated by AI and historical market data. '
    'They are not guaranteed financial advice. Users should perform their own research or consult a '
    'qualified financial advisor before making investment decisions.';

final financialHealthProvider = StateProvider<int>((ref) => 72);

void main() {
  runApp(const ProviderScope(child: SmartWealthPlannerApp()));
}

class SmartWealthPlannerApp extends StatelessWidget {
  const SmartWealthPlannerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Wealth Planner AI',
      theme: ThemeData(colorSchemeSeed: Colors.teal, useMaterial3: true),
      home: const DashboardPage(),
    );
  }
}

class DashboardPage extends ConsumerWidget {
  const DashboardPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final score = ref.watch(financialHealthProvider);
    return Scaffold(
      appBar: AppBar(title: const Text('Smart Wealth Planner AI')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text('Financial Health Score: $score/100', style: Theme.of(context).textTheme.titleLarge),
          const SizedBox(height: 12),
          SizedBox(
            height: 220,
            child: PieChart(
              PieChartData(
                sections: [
                  PieChartSectionData(value: 60, title: 'Equity'),
                  PieChartSectionData(value: 20, title: 'Debt'),
                  PieChartSectionData(value: 10, title: 'Gold'),
                  PieChartSectionData(value: 10, title: 'Cash'),
                ],
              ),
            ),
          ),
          const SizedBox(height: 16),
          const Text('Guided onboarding captures personal info, income, loans, children expenses, monthly expenses, goals, and risk profile.'),
          const SizedBox(height: 12),
          const Text('AI Coach supports: English, Hindi, Hinglish'),
          const SizedBox(height: 16),
          Text(disclaimer, style: Theme.of(context).textTheme.bodySmall),
        ],
      ),
    );
  }
}
